# /etc/letsencrypt/cli.ini — certbot global configuration
# Copy this file to /etc/letsencrypt/cli.ini

# Use logrotate instead of internal log rotation
max-log-backups = 0

# Adjust interactive output regarding automated renewal
preconfigured-renewal = True
